insert into figuras(fig_tipo, fig_nombre, fig_lado)
            values (1, "cua1", 10)
insert into figuras(fig_tipo, fig_nombre, fig_radio)
            values (1, "cir1", 10)
insert into figuras(fig_tipo, fig_nombre, fig_base, fig_altura)
            values (1, "triangulo1", 10, 8.4)
insert into figuras(fig_tipo, fig_nombre, fig_base, fig_altura)
            values (1, "rect1", 10, 8.4)
insert into figuras(fig_tipo, fig_nombre, fig_lado, fig_numlados, fig_apotema)
            values (1, "polig1", 10, 6, 6.2)